language: python
python:
  - "2.6"
env:
  - DJANGO=1.5 DJANGO_SETTINGS_MODULE="leofeed.settings"
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install -r requirements.txt --use-mirrors
before_script:
  - python manage.py syncdb --noinput
script:
  - python manage.py test